# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
#GMAIL_USERNAME: Your_Username
#GMAIL_PASSWORD: Your_Password
#ADMIN_NAME: First User
#ADMIN_EMAIL: user@example.com
#ADMIN_PASSWORD: changeme
#ROLES: [admin, user, VIP]

roles:
  - admin
  - user
  - vip
users:
  admin:
    name: Administrator
    email: admin@example.com
    password: changeme
    roles:
      - admin
      - user
  user:
    name: Joe User
    email: user@example.com
    password: changeme
    roles:
      - user
  user0:
    name: Joe User0
    email: user0@example.com
    password: changeme
    roles:
      - user
  user1:
    name: Joe User1
    email: user1@example.com
    password: changeme
    roles:
      - user
  user2:
    name: Joe User2
    email: user2@example.com
    password: changeme
    roles:
      - user
  user3:
    name: Joe User3
    email: user3@example.com
    password: changeme
    roles:
      - user
  user4:
    name: Joe User4
    email: user4@example.com
    password: changeme
    roles:
      - user
  user5:
    name: Joe User5
    email: user5@example.com
    password: changeme
    roles:
      - user
  user6:
    name: Joe User6
    email: user6@example.com
    password: changeme
    roles:
      - user
  user7:
    name: Joe User7
    email: user7@example.com
    password: changeme
    roles:
      - user
  user8:
    name: Joe User8
    email: user8@example.com
    password: changeme
    roles:
      - user
  user9:
    name: Joe User9
    email: user9@example.com
    password: changeme
    roles:
      - user
  user10:
    name: Joe User10
    email: user10@example.com
    password: changeme
    roles:
      - user
  user11:
    name: Joe User11
    email: user11@example.com
    password: changeme
    roles:
      - user
  user12:
    name: Joe User12
    email: user12@example.com
    password: changeme
    roles:
      - user
  user13:
    name: Joe User13
    email: user13@example.com
    password: changeme
    roles:
      - user
  user14:
    name: Joe User14
    email: user14@example.com
    password: changeme
    roles:
      - user
  user15:
    name: Joe User15
    email: user15@example.com
    password: changeme
    roles:
      - user
  user16:
    name: Joe User16
    email: user16@example.com
    password: changeme
    roles:
      - user
  user17:
    name: Joe User17
    email: user17@example.com
    password: changeme
    roles:
      - user
  user18:
    name: Joe User18
    email: user18@example.com
    password: changeme
    roles:
      - user
  user19:
    name: Joe User19
    email: user19@example.com
    password: changeme
    roles:
      - user
  user20:
    name: Joe User20
    email: user20@example.com
    password: changeme
    roles:
      - user
  user21:
    name: Joe User21
    email: user21@example.com
    password: changeme
    roles:
      - user
  user22:
    name: Joe User22
    email: user22@example.com
    password: changeme
    roles:
      - user
  user23:
    name: Joe User23
    email: user23@example.com
    password: changeme
    roles:
      - user
  user24:
    name: Joe User24
    email: user24@example.com
    password: changeme
    roles:
      - user
  user25:
    name: Joe User25
    email: user25@example.com
    password: changeme
    roles:
      - user
  user26:
    name: Joe User26
    email: user26@example.com
    password: changeme
    roles:
      - user
  user27:
    name: Joe User27
    email: user27@example.com
    password: changeme
    roles:
      - user
  user28:
    name: Joe User28
    email: user28@example.com
    password: changeme
    roles:
      - user
  user29:
    name: Joe User29
    email: user29@example.com
    password: changeme
    roles:
      - user
  user30:
    name: Joe User30
    email: user30@example.com
    password: changeme
    roles:
      - user
  user31:
    name: Joe User31
    email: user31@example.com
    password: changeme
    roles:
      - user
  user32:
    name: Joe User32
    email: user32@example.com
    password: changeme
    roles:
      - user
  user33:
    name: Joe User33
    email: user33@example.com
    password: changeme
    roles:
      - user
  user34:
    name: Joe User34
    email: user34@example.com
    password: changeme
    roles:
      - user
  user35:
    name: Joe User35
    email: user35@example.com
    password: changeme
    roles:
      - user
  user36:
    name: Joe User36
    email: user36@example.com
    password: changeme
    roles:
      - user
  user37:
    name: Joe User37
    email: user37@example.com
    password: changeme
    roles:
      - user
  user38:
    name: Joe User38
    email: user38@example.com
    password: changeme
    roles:
      - user
  user39:
    name: Joe User39
    email: user39@example.com
    password: changeme
    roles:
      - user
  user40:
    name: Joe User40
    email: user40@example.com
    password: changeme
    roles:
      - user
  user41:
    name: Joe User41
    email: user41@example.com
    password: changeme
    roles:
      - user
  user42:
    name: Joe User42
    email: user42@example.com
    password: changeme
    roles:
      - user
  user43:
    name: Joe User43
    email: user43@example.com
    password: changeme
    roles:
      - user
  user44:
    name: Joe User44
    email: user44@example.com
    password: changeme
    roles:
      - user
  user45:
    name: Joe User45
    email: user45@example.com
    password: changeme
    roles:
      - user
  user46:
    name: Joe User46
    email: user46@example.com
    password: changeme
    roles:
      - user
  user47:
    name: Joe User47
    email: user47@example.com
    password: changeme
    roles:
      - user
  user48:
    name: Joe User48
    email: user48@example.com
    password: changeme
    roles:
      - user
  user49:
    name: Joe User49
    email: user49@example.com
    password: changeme
    roles:
      - user
  user50:
    name: Joe User50
    email: user50@example.com
    password: changeme
    roles:
      - user
  user51:
    name: Joe User51
    email: user51@example.com
    password: changeme
    roles:
      - user
  user52:
    name: Joe User52
    email: user52@example.com
    password: changeme
    roles:
      - user
  user53:
    name: Joe User53
    email: user53@example.com
    password: changeme
    roles:
      - user
  user54:
    name: Joe User54
    email: user54@example.com
    password: changeme
    roles:
      - user
  user55:
    name: Joe User55
    email: user55@example.com
    password: changeme
    roles:
      - user
  user56:
    name: Joe User56
    email: user56@example.com
    password: changeme
    roles:
      - user
  user57:
    name: Joe User57
    email: user57@example.com
    password: changeme
    roles:
      - user
  user58:
    name: Joe User58
    email: user58@example.com
    password: changeme
    roles:
      - user
  user59:
    name: Joe User59
    email: user59@example.com
    password: changeme
    roles:
      - user
  user60:
    name: Joe User60
    email: user60@example.com
    password: changeme
    roles:
      - user
  user61:
    name: Joe User61
    email: user61@example.com
    password: changeme
    roles:
      - user
  user62:
    name: Joe User62
    email: user62@example.com
    password: changeme
    roles:
      - user
  user63:
    name: Joe User63
    email: user63@example.com
    password: changeme
    roles:
      - user
  user64:
    name: Joe User64
    email: user64@example.com
    password: changeme
    roles:
      - user
  user65:
    name: Joe User65
    email: user65@example.com
    password: changeme
    roles:
      - user
  user66:
    name: Joe User66
    email: user66@example.com
    password: changeme
    roles:
      - user
  user67:
    name: Joe User67
    email: user67@example.com
    password: changeme
    roles:
      - user
  user68:
    name: Joe User68
    email: user68@example.com
    password: changeme
    roles:
      - user
  user69:
    name: Joe User69
    email: user69@example.com
    password: changeme
    roles:
      - user
  user70:
    name: Joe User70
    email: user70@example.com
    password: changeme
    roles:
      - user
  user71:
    name: Joe User71
    email: user71@example.com
    password: changeme
    roles:
      - user
  user72:
    name: Joe User72
    email: user72@example.com
    password: changeme
    roles:
      - user
  user73:
    name: Joe User73
    email: user73@example.com
    password: changeme
    roles:
      - user
  user74:
    name: Joe User74
    email: user74@example.com
    password: changeme
    roles:
      - user
  user75:
    name: Joe User75
    email: user75@example.com
    password: changeme
    roles:
      - user
  user76:
    name: Joe User76
    email: user76@example.com
    password: changeme
    roles:
      - user
  user77:
    name: Joe User77
    email: user77@example.com
    password: changeme
    roles:
      - user
  user78:
    name: Joe User78
    email: user78@example.com
    password: changeme
    roles:
      - user
  user79:
    name: Joe User79
    email: user79@example.com
    password: changeme
    roles:
      - user
  user80:
    name: Joe User80
    email: user80@example.com
    password: changeme
    roles:
      - user
  user81:
    name: Joe User81
    email: user81@example.com
    password: changeme
    roles:
      - user
  user82:
    name: Joe User82
    email: user82@example.com
    password: changeme
    roles:
      - user
  user83:
    name: Joe User83
    email: user83@example.com
    password: changeme
    roles:
      - user
  user84:
    name: Joe User84
    email: user84@example.com
    password: changeme
    roles:
      - user
  user85:
    name: Joe User85
    email: user85@example.com
    password: changeme
    roles:
      - user
  user86:
    name: Joe User86
    email: user86@example.com
    password: changeme
    roles:
      - user
  user87:
    name: Joe User87
    email: user87@example.com
    password: changeme
    roles:
      - user
  user88:
    name: Joe User88
    email: user88@example.com
    password: changeme
    roles:
      - user
  user89:
    name: Joe User89
    email: user89@example.com
    password: changeme
    roles:
      - user
  user90:
    name: Joe User90
    email: user90@example.com
    password: changeme
    roles:
      - user
  user91:
    name: Joe User91
    email: user91@example.com
    password: changeme
    roles:
      - user
  user92:
    name: Joe User92
    email: user92@example.com
    password: changeme
    roles:
      - user
  user93:
    name: Joe User93
    email: user93@example.com
    password: changeme
    roles:
      - user
  user94:
    name: Joe User94
    email: user94@example.com
    password: changeme
    roles:
      - user
  user95:
    name: Joe User95
    email: user95@example.com
    password: changeme
    roles:
      - user
  user96:
    name: Joe User96
    email: user96@example.com
    password: changeme
    roles:
      - user
  user97:
    name: Joe User97
    email: user97@example.com
    password: changeme
    roles:
      - user
  user98:
    name: Joe User98
    email: user98@example.com
    password: changeme
    roles:
      - user
  user99:
    name: Joe User99
    email: user99@example.com
    password: changeme
    roles:
      - user
